function this_curve = build_curve(events,baseline,duration,dt,filter_bins)

this_curve = zeros(1,floor(duration/dt)) + baseline;
    
for j = 1:size(events,1)

    tau = events(j,[2 3]);
    ef = genEfilt_ar(tau,filter_bins);
    [~, this_curve, ~] = addSpike_ar(events(j,4),...
                                        this_curve, 0, ef, ...
                                        events(j,1),...
                                        tau,...
                                        zeros(size(this_curve)), ...
                                        events(j,4), ...
                                        2, 1, 1);

end
